<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.10</version>
        <relativePath/>
    </parent>

    <groupId>io.docpilot</groupId>
    <artifactId>docpilot</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>docpilot-shared</module>
        <module>docpilot-block</module>
        <module>docpilot-filesystem</module>
        <module>docpilot-services</module>
    </modules>

    <properties>
        <java.version>25</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <flexmark.version>0.64.8</flexmark.version>
        <lombok.version>1.18.42</lombok.version>
        <aws.sdk.version>2.41.1</aws.sdk.version>
        <commons-io.version>2.18.0</commons-io.version>
        <java-jwt.version>4.4.0</java-jwt.version>
        <docpilot.version>1.0-SNAPSHOT</docpilot.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.docpilot</groupId>
                <artifactId>docpilot-common</artifactId>
                <version>${docpilot.version}</version>
            </dependency>

            <dependency>
                <groupId>io.docpilot</groupId>
                <artifactId>docpilot-web-common</artifactId>
                <version>${docpilot.version}</version>
            </dependency>

            <dependency>
                <groupId>io.docpilot</groupId>
                <artifactId>docpilot-ai-service</artifactId>
                <version>${docpilot.version}</version>
            </dependency>

            <dependency>
                <groupId>io.docpilot</groupId>
                <artifactId>docpilot-block</artifactId>
                <version>${docpilot.version}</version>
            </dependency>

            <dependency>
                <groupId>io.docpilot</groupId>
                <artifactId>docpilot-document-service</artifactId>
                <version>${docpilot.version}</version>
            </dependency>

            <dependency>
                <groupId>io.docpilot</groupId>
                <artifactId>docpilot-user-service</artifactId>
                <version>${docpilot.version}</version>
            </dependency>

            <dependency>
                <groupId>io.docpilot</groupId>
                <artifactId>docpilot-filesystem</artifactId>
                <version>${docpilot.version}</version>
            </dependency>

            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>s3</artifactId>
                <version>${aws.sdk.version}</version>
            </dependency>

            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>${commons-io.version}</version>
            </dependency>

            <dependency>
                <groupId>com.auth0</groupId>
                <artifactId>java-jwt</artifactId>
                <version>${java-jwt.version}</version>
            </dependency>

            <dependency>
                <groupId>com.vladsch.flexmark</groupId>
                <artifactId>flexmark</artifactId>
                <version>${flexmark.version}</version>
            </dependency>

            <dependency>
                <groupId>com.vladsch.flexmark</groupId>
                <artifactId>flexmark-ext-tables</artifactId>
                <version>${flexmark.version}</version>
            </dependency>

            <dependency>
                <groupId>com.vladsch.flexmark</groupId>
                <artifactId>flexmark-ext-gfm-tasklist</artifactId>
                <version>${flexmark.version}</version>
            </dependency>

            <dependency>
                <groupId>com.vladsch.flexmark</groupId>
                <artifactId>flexmark-ext-gfm-strikethrough</artifactId>
                <version>${flexmark.version}</version>
            </dependency>

            <dependency>
                <groupId>com.vladsch.flexmark</groupId>
                <artifactId>flexmark-ext-autolink</artifactId>
                <version>${flexmark.version}</version>
            </dependency>

            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <optional>true</optional>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <configuration>
                        <annotationProcessorPaths>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                                <version>${lombok.version}</version>
                            </path>
                        </annotationProcessorPaths>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>
