export const TABLE_DIVIDER_GUTTER_PX = 8
export const TABLE_DIVIDER_REVEAL_DELAY_MS = 160
export const TABLE_DIVIDER_HOTSPOT_RADIUS_PX = 22
export const TABLE_HOVER_INDICATOR_DOT_ANCHOR_OUTSET_PX = 18
export const TABLE_HOVER_INDICATOR_HIDE_DELAY_MS = 240
export const TABLE_HOVER_INDICATOR_RAIL_SIZE_PX = 12
