package io.docpilot.ai.model;

import lombok.Getter;
import lombok.Setter;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Provider-neutral token usage summary.
 */
@Getter
@Setter
public class ChatUsage implements AdditionalPropertiesCarrier {

    /**
     * Tokens consumed by the prompt or input side.
     */
    private Integer inputTokens;

    /**
     * Tokens generated by the model.
     */
    private Integer outputTokens;

    /**
     * Total tokens reported by the provider.
     */
    private Integer totalTokens;

    /**
     * Extension fields for provider-specific usage breakdowns.
     */
    private final Map<String, Object> additionalProperties = new LinkedHashMap<>();

}
